nav:
    - Home: index.md
    - User Guide:
          - user_guide/index.md
          - Getting Started: user_guide/getting_started.md
          - Features: user_guide/features.md
          - Loss Functions: user_guide/loss_functions.md
          - Algorithms:
                - user_guide/algorithms/index.md
                - Eagle3: user_guide/algorithms/eagle3.md
                - Dflash: user_guide/algorithms/dflash.md
                - DSpark: user_guide/algorithms/dspark.md
                - P-Eagle: user_guide/algorithms/peagle.md
                - MTP: user_guide/algorithms/mtp.md
                - Decision Guide: user_guide/algorithms/decision_guide.md
          - Tutorials:
                - user_guide/tutorials/index.md
                - Train a Speculator: user_guide/tutorials/train.md
                - Response Regeneration: user_guide/tutorials/response_regeneration.md
                - Evaluating Model Performance: user_guide/tutorials/evaluating_performance.md
                - Serve in vLLM: user_guide/tutorials/serve_vllm.md
    - Developer Guide:
          - developer/index.md
          - Contributing Guide: developer/contributing.md
          - Code of Conduct: developer/code_of_conduct.md
          - Add New Spec Decode Algorithm: developer/add_algorithm.md
          - Design Documents: developer/design_docs.md
          - Branding Guidelines: developer/branding.md
    - API Reference:
          - api/index.md
          - reference/speculators
    - CLI Reference:
          - cli/index.md
          - prepare-data: cli/prepare_data.md
          - data_generation_offline.py: cli/data_generation_offline.md
          - launch_vllm.py: cli/launch_vllm.md
          - train.py: cli/train.md
          - response_regeneration: cli/response_regeneration.md
    - Community:
          - community/index.md
          - Contact Us: community/contact_us.md
          - Events & Meetups: community/meetups.md
          - Slack: https://slack.vllm.ai
          - Blog: https://vllm.ai/blog/tags/speculative-decoding
